# Import modules 


In [1]:
import ROI 
from ROI import *

C:\Users\mEtrOpOliS\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
# 4x4 feature map with only 1 channel
input_value =  [[
    [[5,0,2], [2,0,4], [4,6,9], [4,8,7]],
    [[7,6,3], [44,55,6], [51,78,8], [2,66,33]],
    [[9,23,11], [12, 7,8], [1,88,55], [7,63,33]],
    [[11,44,29], [13,4,8], [2,5,6], [58,78,9]]
]]
input_value = np.asarray(input_value, dtype='int32')
# regions of interest as lists of:
# feature map index, upper left, bottom right coordinates
rois_value = [
    [0, 0, 11, 33],
    [ 3, 12, 15, 13],
    [1, 10, 13, 12], 
    [11, 11, 13, 12]
]
rois_value = np.asarray(rois_value, dtype='int32')
#input_featuremap = tf.placeholder(tf.float32)
rois = tf.placeholder(tf.int32)
input_const = tf.constant(input_value, tf.float32)
rois_const = tf.constant(rois_value, tf.int32)
x=ROI(4,4)
y=x.channels(input_const)
list_input=[ input_const, rois_const]
final_output= x.compute(list_input)

# Display the results

In [3]:
#initialize the variable
init_op = tf.initialize_all_variables()

#run the graph
with tf.Session() as sess:
    sess.run(init_op) #execute init_op
    #print the random values that we sample
    print (sess.run(final_output))

final_output.shape

Instructions for updating:
Use `tf.global_variables_initializer` instead.
[[[[ 5.  0.  2.]
   [ 2.  0.  4.]
   [ 4.  6.  9.]
   [ 4.  8.  7.]]

  [[ 7.  6.  3.]
   [44. 55.  6.]
   [51. 78.  8.]
   [ 2. 66. 33.]]

  [[ 9. 23. 11.]
   [12.  7.  8.]
   [ 1. 88. 55.]
   [ 7. 63. 33.]]

  [[11. 44. 29.]
   [13.  4.  8.]
   [ 2.  5.  6.]
   [58. 78.  9.]]]


 [[[ 5.  0.  2.]
   [ 2.  0.  4.]
   [ 4.  6.  9.]
   [ 4.  8.  7.]]

  [[ 7.  6.  3.]
   [44. 55.  6.]
   [51. 78.  8.]
   [ 2. 66. 33.]]

  [[ 9. 23. 11.]
   [12.  7.  8.]
   [ 1. 88. 55.]
   [ 7. 63. 33.]]

  [[11. 44. 29.]
   [13.  4.  8.]
   [ 2.  5.  6.]
   [58. 78.  9.]]]


 [[[ 5.  0.  2.]
   [ 2.  0.  4.]
   [ 4.  6.  9.]
   [ 4.  8.  7.]]

  [[ 7.  6.  3.]
   [44. 55.  6.]
   [51. 78.  8.]
   [ 2. 66. 33.]]

  [[ 9. 23. 11.]
   [12.  7.  8.]
   [ 1. 88. 55.]
   [ 7. 63. 33.]]

  [[11. 44. 29.]
   [13.  4.  8.]
   [ 2.  5.  6.]
   [58. 78.  9.]]]


 [[[ 5.  0.  2.]
   [ 2.  0.  4.]
   [ 4.  6.  9.]
   [ 4.  8.  7.]]

  [[ 7.  6

TensorShape([Dimension(4), Dimension(4), Dimension(4), Dimension(3)])

# Try to change the number of regions and you should a change in the shape of final_outputs 


# Try to change max values in the input you will see changes in the output 

In [4]:
input_value = [[
    [[100], [200], [440], [4]],
    [[3], [4], [12], [2]],
    [[86], [55], [88], [70]],
    [[1], [330], [120], [58]]
]]

input_value = np.asarray(input_value, dtype='int32')
# regions of interest as lists of:
# feature map index, upper left, bottom right coordinates
rois_value = [
    [0, 0, 11, 33],
    [ 3, 12, 15, 13],
    [1, 10, 13, 12]
]
rois_value = np.asarray(rois_value, dtype='int32')
input_featuremap = tf.placeholder(tf.float32)
rois = tf.placeholder(tf.int32)
input_const = tf.constant(input_value, tf.float32)
rois_const = tf.constant(rois_value, tf.int32)


x=ROI(3,3)

x.channels(input_featuremap)
list_input=[ input_const, rois_const]
final_output=x.compute(list_input)
with tf.Session() as sess:
    sess.run(init_op) #execute init_op
    #print the random values that we sample
    print (sess.run(final_output))

final_output.shape

[[[[100.      ]
   [280.      ]
   [149.33331 ]]

  [[ 30.66667 ]
   [ 26.444447]
   [ 28.88889 ]]

  [[ 29.333328]
   [195.33334 ]
   [ 77.77777 ]]]


 [[[100.      ]
   [280.      ]
   [149.33331 ]]

  [[ 30.66667 ]
   [ 26.444447]
   [ 28.88889 ]]

  [[ 29.333328]
   [195.33334 ]
   [ 77.77777 ]]]


 [[[100.      ]
   [280.      ]
   [149.33331 ]]

  [[ 30.66667 ]
   [ 26.444447]
   [ 28.88889 ]]

  [[ 29.333328]
   [195.33334 ]
   [ 77.77777 ]]]]


TensorShape([Dimension(3), Dimension(3), Dimension(3), Dimension(1)])